"""empty message

Revision ID: 175f698d45e3
Revises: 0e4becb00c09
Create Date: 2022-01-09 21:31:25.401631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175f698d45e3'
down_revision = '0e4becb00c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=200), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
